### ISSUE TITLE
startup.sh not running automatically

### ISSUE THREAD

**Issue by rcalv002** [spurin/container-systemd-sshd-ttyd#1]
Hi James,

Tried to build this locally and it builds. however when attempting to login via ssh I'm having several issues

- ssh service is not automatically running. Connect to box and run systemctl status ssh it shows enabled but off. Do a systemctl start ssh, it then turns on and is reachable.
- startup.sh seems to not run automatically even though it should be triggered via startup.service. run /bin/statup.sh manually and then it creates the guest user and sets pass, etc.

Don't see any errors in the build or container startup referencing it tries to do this but fails.
running directly from your image on docker hub its a different problem.

in both cases ttyd web seems to startup without issue

**Comment by spurin** [comment]
Hi Richard,

Good to hear from you again.  I'm guessing you're using the previous execution example execution from the spurin/container-systemd rather than in the one specific to this repo (which is slightly different), for reference it is -

```
CONTAINER=$(docker run -p 7681:7681 -p 2222:22 -d --privileged spurin/container-systemd-sshd-ttyd:ubuntu_21.04)
docker exec -it $CONTAINER bash
```

To explain what's happening.  All of these images use the same container-entrypoint.sh script.  If you look at the following lines -

https://github.com/spurin/container-systemd/blob/ubuntu_21.10/container-entrypoint.sh#L59-L64

There's two logic gates, one of them is for if a command is being passed, i.e. /bin/bash, the other is if there's no command, i.e. the default entrypoint.

If /bin/bash or another command is passed as an argument, a custom systemd entrypoint is created (https://github.com/spurin/container-systemd/blob/ubuntu_21.10/container-entrypoint.sh#L12-L44).  This is then executed at startup.  When this happens, this is the only service that systemd starts as it's a custom entrypoint.

If no command is provided, systemd starts and then will automatically try to start all enabled services (ssh in this case, is already enabled as per the Dockerfile).

This is the reason why I left the previous execution example off the README as this stage of the container build, i.e. customisation with specific services is best used without any commands being passed.  

I would personally only use the previous approach (passing /bin/bash) for debugging/troubleshooting purposes.  If you do, you'll need to manually start any services that you require.

**Comment by rcalv002** [comment]
Excellent. Sorry about that

**Comment by spurin** [comment]
> Excellent. Sorry about that

No need to apologise Richard, am really happy to see you're thoroughly testing and using them.

I'll update the readme accordingly so that this is better understood for all
